# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: "pgxcli-windows-amd64"
    main: "./cmd/pgxcli"
    binary: "pgxcli"
    env:
      - CGO_ENABLED=1
      - CC=gcc
      - CXX=g++
    goos:
      - windows
    goarch:
      - amd64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}

archives:
  - id: default
    formats: ["zip"]
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}
    files:
      - "LICENSE"
      - "README.md"

chocolateys:
  - name: "pgxcli"
    owners: "Balaji J"
    title: "pgxcli"
    authors: "Balaji J"
    project_url: "https://github.com/Balaji01-4D/pgxcli"
    license_url: "https://github.com/Balaji01-4D/pgxcli/blob/main/LICENSE"
    project_source_url: "https://github.com/Balaji01-4D/pgxcli"
    docs_url: "https://github.com/Balaji01-4D/pgxcli/blob/main/README.md"
    bug_tracker_url: "https://github.com/Balaji01-4D/pgxcli/issues"
    tags: "cli database postgres postgresql"
    summary: "An interactive PostgreSQL CLI written in Go."
    description: |
      pgxcli is an interactive PostgreSQL CLI written in Go.
    api_key: "{{ .Env.CHOCOLATEY_API_KEY }}"
    skip_publish: false

checksum:
  name_template: "checksums-windows.txt"