# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: "pgxcli-darwin"
    main: "./cmd/pgxcli"
    binary: "pgxcli"
    env:
      - CGO_ENABLED=1
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}

archives:
  - id: default
    formats: ["tar.gz"]
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}
    files:
      - "LICENSE"
      - "README.md"

homebrew_casks:
  - name: "pgxcli"
    repository:
      owner: "Balaji01-4D"
      name: "homebrew-pgxcli"
      token: "{{ .Env.TAP_GITHUB_TOKEN }}"
    commit_author:
      name: "Balaji J"
      email: "balaji.jothi.in@gmail.com"
    homepage: "https://github.com/Balaji01-4D/pgxcli"
    description: "An interactive PostgreSQL CLI written in Go"
    license: "MIT"
    dependencies:
      - formula: "less"
    binaries:
      - "pgxcli"
    hooks:
      post:
        install: |
          if OS.mac?
            system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/pgxcli"]
          end

checksum:
  name_template: "checksums-darwin.txt"