# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2

project_name: pgxcli

release:
  draft: true
  prerelease: auto
  name_template: "pgxcli {{.Version}}"

before:
  hooks:
    - go mod tidy

builds:
  - id: linux
    main: ./cmd/pgxcli
    binary: bin/pgxcli
    goos: [linux]
    goarch: [amd64, arm64]
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}

  - id: darwin
    main: ./cmd/pgxcli
    binary: bin/pgxcli
    goos: [darwin]
    goarch: [amd64, arm64]
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}

  - id: windows
    main: ./cmd/pgxcli
    binary: bin/pgxcli
    goos: [windows]
    goarch: [amd64]
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}

archives:
  - id: linux-archive
    ids: [linux]
    formats: [tar.gz]
    name_template: "pgxcli_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    wrap_in_directory: true
    files:
      - LICENSE
      - README.md

  - id: darwin-archive
    ids: [darwin]
    formats: [tar.gz]
    name_template: "pgxcli_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    wrap_in_directory: true
    files:
      - LICENSE
      - README.md

  - id: windows-archive
    ids: [windows]
    formats: [zip]
    name_template: "pgxcli_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    wrap_in_directory: false
    files:
      - LICENSE
      - README.md

nfpms:
  - ids: [linux]
    vendor: "Balaji J"
    maintainer: "Balaji J <balaji.jothi.in@gmail.com>"
    description: "An interactive PostgreSQL CLI written in Go"
    homepage: "https://github.com/Balaji01-4D/pgxcli"
    license: "MIT"
    bindir: /usr/bin
    formats:
      - deb
      - rpm
      - apk
      - archlinux

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"